### ISSUE TITLE
Making typing.Type injectable.

### ISSUE THREAD

**Issue by romangraef** [allrod5/injectable#28] opened 2020-06-19 16:53 UTC
## Introduction

I am currently into an issue where i need the Type of all `@injectable` objects. These objects have a common supertype, but no empty `__init__`, so I can't just use  `Autowired(List[BaseType])`. Concrete, this is a database project, and the model classes need to be registered so they can be created in the database.

<sub>This is kinda far fetched, and i could definitely see why this would be rejected, as database models are kind of the only usecase i coud think of, and it is kind of narrow.</sub>

## Feature Request

Allowing the `Autowired(Type[BaseType])` to pick up an injectable subclass of a `BaseType`, or `Autowired(List[Type[BaseType]])` to get all injectable subclasses. Maybe this could be indicated by `@injectable(type=True)`.

_By submiting an issue I accept this project's
[Code of Conduct](https://github.com/allrod5/injectable/blob/master/CODE_OF_CONDUCT.md). Any issue out of
these guidelines can be deleted at any moment without further explanation._

**Comment by allrod5** [comment] 2020-06-19 17:22
Hi @romangraef! Thank you for the issue with implementation suggestions details :hearts: 

Could you provide a minimal working example of how you're using injectable today? I fear I wasn't fully able to see it through. With a concrete example, it will be easier to spot the issue's root cause and think of the best way out of it.

**Comment by romangraef** [comment] 2020-06-19 18:22
I created a gist with a minimal (not) working sample of what i tried. In case you don't know `peewee` (a sql orm), the most important function in order to understand this gist should be engine.create_tables() which accepts an array of table classes, which it then creates in the database.

https://gist.github.com/romangraef/584f8c075143412dd0f681a5b189e440

**Comment by allrod5** [comment] 2020-06-19 20:49
Thank you for the gist @romangraef. I've run it and it does give me an error due to the `Type` wrapper. I've removed the `Type` wrapper and just used `tables: Autowired(typing.List[TableBase])` and it worked.

Sorry, I think that I didn't get it when you said you can't use `Autowired(List[BaseType])`, especially the "no empty `__init__`" thing. Can you clarify this for me?

**Comment by allrod5** [comment] 2020-06-19 22:09
Injectables mustn't depend on mandatory arguments. In case arguments are needed for instantiation one should declare an injectable_factory to correctly instantiate objects.

Currently, I don't see a real benefit in allowing wrapping types with `Type`. It is odd that one would want an object of type `Type` and most probably `typing.Type` isn't intended for that kind of usage.

I'm really glad that you solved your issue :tada: Please, feel free to open other issues if you find it necessary or to post a question at StackOverflow with the `python-injectable` tag.

_As the issue seems solved I'm closing it. If you believe that it should be reopened just leave a comment and I'll review it._

**Closed by allrod5** 2020-06-19 22:09 UTC
Labels: new feature, triage
